### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zhemingbuhuichong** [HJDCZY/tju_unipus#1]
python版本为3.12，如图
config配置如图
在第四步时会闪退，出现窗口后消失，大佬有没有解决方法
<img width="217" alt="屏幕截图 2024-04-18 122805" src="https://github.com/HJDCZY/tju_unipus/assets/126929929/2a44a37f-a5d6-40d7-9f80-574e86986e71">
<img width="665" alt="屏幕截图 2024-04-18 123434" src="https://github.com/HJDCZY/tju_unipus/assets/126929929/6d3e6c61-bfdc-4d86-be56-716bd222f1cf">

**Comment by HJDCZY** [comment]
我可能需要更多的信息，首先，请删除你第二行到第六行的内容（恢复到我当时发的只有两个引号）
![image](https://github.com/HJDCZY/tju_unipus/assets/112754310/e0dbfab0-68cb-4395-af8a-2a82b1e2aa52)，确保你的chromelocation和chromedriverlocation正确
我怀疑你的用户名和密码上有反斜杠之类的字符，请在前面引号外加上"r"（就和user.chormelocation和user.chormedriverlocation一样）
对于你的设备，我们可能要进行debug，你可以在unipus.py的任何位置加上"input("按Enter继续...")"来让程序停住进行debug。闪退的原因一般是程序运行一半之后报错，然后窗口自动关掉了。

这玩意源码真不难，你甚至可以自己读一读改一改

**Comment by zhemingbuhuichong** [comment]
成了，谢谢大佬

**Comment by HJDCZY** [comment]
ok，记得把我代码优化下，或者加几本书 : )
