### ISSUE TITLE
v0.0.2

### ISSUE THREAD

**Issue by zzzzzzzzzzzq** [HJDCZY/tju_unipus#3]
请问这个还能用吗，我按照说明做完了之后还是报readme的路径错误，但是已经充分检查了。。。

**Comment by zzzzzzzzzzzq** [comment]
![微信图片_20240604160050](https://github.com/HJDCZY/tju_unipus/assets/114342119/58a10c9e-86c4-4bb5-bce8-01a9abe2dd6a)

**Comment by HJDCZY** [comment]
chrome和chromedriver的版本要一致，我提供的chrome版本和chromedriver的版本是一致的，你可以用我的，没必要用你自己的

**Comment by zzzzzzzzzzzq** [comment]
> chrome和chromedriver的版本要一致，我提供的chrome版本和chromedriver的版本是一致的，你可以用我的，没必要用你自己的

谢谢，这个我已经修改了，但是还是不行
![image](https://github.com/HJDCZY/tju_unipus/assets/114342119/ad6aa2fc-785a-448c-9ea9-d0bfcf12cc82)
而且无论是有没有vpn也考虑了，那个黑框总是一闪而过... 请问还有什么要注意的问题吗

**Comment by HJDCZY** [comment]
emmm，确保你的exe文件和ini文件在同一目录下，实在不行你去用v0.0.1的源码吧QAQ

**Comment by Xigongjiexian1** [comment]
> > chrome和chromedriver的版本要一致，我提供的chrome版本和chromedriver的版本是一致的，你可以用我的，没必要用你自己的
> 
> 谢谢，这个我已经修改了，但是还是不行 ![image](https://private-user-images.githubusercontent.com/114342119/336413336-ad6aa2fc-785a-448c-9ea9-d0bfcf12cc82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTgzNzQsIm5iZiI6MTcxODE1ODA3NCwicGF0aCI6Ii8xMTQzNDIxMTkvMzM2NDEzMzM2LWFkNmFhMmZjLTc4NWEtNDQ4Yy05ZWE5LWQwYmZjZjEyY2M4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhNDJkZGUwN2ZhODU2YTQ0YWE2YjJmZjQwNmMzZDc4N2ZjNDk5MzEyNDEzMWQ1NTQ3MjVkOTBkZDk0ZDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1N2BRyZQ1T7gNCsuQp55hmK_20g2qG_ipmptYha4pnY) 而且无论是有没有vpn也考虑了，那个黑框总是一闪而过... 请问还有什么要注意的问题吗

俺也一样

**Comment by HJDCZY** [comment]
> > > chrome和chromedriver的版本要一致，我提供的chrome版本和chromedriver的版本是一致的，你可以用我的，没必要用你自己的
> > 
> > 
> > 谢谢，这个我已经修改了，但是还是不行 ![image](https://private-user-images.githubusercontent.com/114342119/336413336-ad6aa2fc-785a-448c-9ea9-d0bfcf12cc82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTgzNzQsIm5iZiI6MTcxODE1ODA3NCwicGF0aCI6Ii8xMTQzNDIxMTkvMzM2NDEzMzM2LWFkNmFhMmZjLTc4NWEtNDQ4Yy05ZWE5LWQwYmZjZjEyY2M4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhNDJkZGUwN2ZhODU2YTQ0YWE2YjJmZjQwNmMzZDc4N2ZjNDk5MzEyNDEzMWQ1NTQ3MjVkOTBkZDk0ZDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1N2BRyZQ1T7gNCsuQp55hmK_20g2qG_ipmptYha4pnY) 而且无论是有没有vpn也考虑了，那个黑框总是一闪而过... 请问还有什么要注意的问题吗
> 
> 俺也一样

那就建议0.0.1版本去找源码了，我看不到你上传的图片

**Comment by HJDCZY** [comment]
> > > chrome和chromedriver的版本要一致，我提供的chrome版本和chromedriver的版本是一致的，你可以用我的，没必要用你自己的
> > 
> > 
> > 谢谢，这个我已经修改了，但是还是不行 ![image](https://private-user-images.githubusercontent.com/114342119/336413336-ad6aa2fc-785a-448c-9ea9-d0bfcf12cc82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTgzNzQsIm5iZiI6MTcxODE1ODA3NCwicGF0aCI6Ii8xMTQzNDIxMTkvMzM2NDEzMzM2LWFkNmFhMmZjLTc4NWEtNDQ4Yy05ZWE5LWQwYmZjZjEyY2M4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhNDJkZGUwN2ZhODU2YTQ0YWE2YjJmZjQwNmMzZDc4N2ZjNDk5MzEyNDEzMWQ1NTQ3MjVkOTBkZDk0ZDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1N2BRyZQ1T7gNCsuQp55hmK_20g2qG_ipmptYha4pnY) 而且无论是有没有vpn也考虑了，那个黑框总是一闪而过... 请问还有什么要注意的问题吗
> 
> 俺也一样

那就建议0.0.1版本去找源码了，我看不到你上传的图片
